import { Question, QuestionBank, StudyMaterial, User, ActivityLog } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'u1_student',
    email: 'drstudent@example.com',
    fullName: 'Dr. Kathir Student',
    role: 'Student',
    isActive: true,
    createdAt: '2026-06-13T12:00:00Z',
  },
  {
    id: 'u2_admin',
    email: 'mrcpchadmin@example.com',
    fullName: 'Dr. Alice Roberts (Admin)',
    role: 'Admin',
    isActive: true,
    createdAt: '2026-06-12T12:00:00Z',
  },
  {
    id: 'u3_superadmin',
    email: 'superadmin@example.com',
    fullName: 'Senior Board Chair (SuperAdmin)',
    role: 'SuperAdmin',
    isActive: true,
    createdAt: '2026-06-10T12:00:00Z',
  },
];

export const INITIAL_BANKS: QuestionBank[] = [
  {
    id: 'qb_cards',
    name: 'Cardiology Core Essentials',
    description: 'High-yield cardiology questions covering congenital anomalies, murmurs, and ECG findings.',
    category: 'Cardiology',
    createdBy: 'u2_admin',
    createdAt: '2026-06-14T01:05:00Z',
    questionCount: 3,
  },
  {
    id: 'qb_neonatal',
    name: 'Neonatal & Prematurity Care',
    description: 'Advanced neonatal medicine, incubator care, respiratory distress, and metabolic emergencies.',
    category: 'Neonatal',
    createdBy: 'u2_admin',
    createdAt: '2026-06-14T01:10:00Z',
    questionCount: 2,
  },
  {
    id: 'qb_respiratory',
    name: 'Pediatric Pulmonology & Allergy',
    description: 'Common upper/lower airway conditions, asthma guidelines, and allergy profiles in children.',
    category: 'Respiratory',
    createdBy: 'u2_admin',
    createdAt: '2026-06-14T01:15:00Z',
    questionCount: 1,
  },
];

export const INITIAL_QUESTIONS: Question[] = [
  {
    id: 'q_card1',
    bankId: 'qb_cards',
    question: 'A 2-month-old infant is brought to clinic due to feeding difficulties and diaphoresis when breastfeeding. On examination, there is a harsh pansystolic murmur heard loudest at the left lower sternal border (LLSB). What is the most likely diagnosis?',
    options: [
      'Ventricular Septal Defect (VSD)',
      'Atrial Septal Defect (ASD)',
      'Patent Ductus Arteriosus (PDA)',
      'Tetralogy of Fallot',
    ],
    correctAnswer: 0,
    explanation: 'A harsh holosystolic/pansystolic murmur at the left lower sternal border in an infant presenting with feeding difficulties and poor weight gain is highly characteristic of a moderate-to-large Ventricular Septal Defect (VSD).',
    tags: ['VSD', 'Murmur', 'Congenital-Anomalies'],
    difficulty: 'Medium',
    createdAt: '2026-06-14T01:05:00Z',
  },
  {
    id: 'q_card2',
    bankId: 'qb_cards',
    question: 'A parent brings their 4-year-old child who experienced a transient loss of consciousness while crying intensely after scraping her knee. She turned blue, went limp, but recovered fully within 30 seconds. What is the appropriate management?',
    options: [
      'Immediate Pediatric Cardiology Referral',
      'Reassurance and Education on Breath-Holding Spells',
      'Start Oral Propranolol Therapy',
      'Arrange an Urgent 24-Hour ambulatory ECG',
    ],
    correctAnswer: 1,
    explanation: 'This scenario describes a classic cyanotic Breath-holding Spell, which is a benign, paroxysmal non-epileptic event common in children aged 6 months to 6 years. Reassurance is the key mainstay of treatment.',
    tags: ['Autonomic', 'Fainting', 'Breath-holding'],
    difficulty: 'Easy',
    createdAt: '2026-06-14T01:06:00Z',
  },
  {
    id: 'q_card3',
    bankId: 'qb_cards',
    question: 'Which of the following clinical features is pathognomonic of Coarctation of the Aorta in a neonate presenting with acute cardiogenic shock?',
    options: [
      'Wide pulse pressure with bounding pulses',
      'Significant blood pressure and femoral pulse delay/differential between upper and lower limbs',
      'Harsh diastolic murmur at the apex',
      'Isolated right axis deviation on electrocardiogram',
    ],
    correctAnswer: 1,
    explanation: 'Coarctation of the aorta is a duct-dependent systemic lesion. Closure of the ductus arteriosus causes severe shock. Perfusion delay to lower limbs gives rise to distinct femoral pulse delays and blood pressure gradients.',
    tags: ['Coarctation', 'Pulses', 'Duct-dependent'],
    difficulty: 'Hard',
    createdAt: '2026-06-14T01:07:00Z',
  },
  {
    id: 'q_neo1',
    bankId: 'qb_neonatal',
    question: 'A preterm male infant delivered at 30 weeks gestation presents with respiratory distress including expiratory grunting, nasal flaring, and chest recessions within minutes of birth. Chest radiograph demonstrates a diffuse ground-glass appearance and air bronchograms. What is the primary underlying pathophysiology?',
    options: [
      'Deficiency of surfactant causing alveoli collapse',
      'Ineffective clearance of fetal lung fluid',
      'In-utero infection causing focal consolidation',
      'Echocardiographic evidence of right-to-left shunting',
    ],
    correctAnswer: 0,
    explanation: 'Respiratory Distress Syndrome (RDS) is caused by a surfactant deficiency inside immature lungs. Collapsed alveoli cause the radiographic ground-glass and clear-cut air bronchograms.',
    tags: ['RDS', 'Surfactant', 'Prematurity'],
    difficulty: 'Medium',
    createdAt: '2026-06-14T01:10:00Z',
  },
  {
    id: 'q_neo2',
    bankId: 'qb_neonatal',
    question: 'A term neonate presents with severe jaundice on Day 2 of life. The serum total bilirubin is rapidly rising and has crossed the exchange transfusion threshold. Blood typing reveals Maternal type O-positive and Infant type A-positive. What test should be ordered next to confirm immune hemolysis?',
    options: [
      'Direct Antiglobulin Test (DAT / Coombs Test)',
      'G6PD enzyme assay',
      'Maternal antibody screen',
      'Hemoglobin electrophoresis',
    ],
    correctAnswer: 0,
    explanation: 'In ABO incompatibility hyperbilirubinemia, a Direct Antiglobulin Test (DAT/Coombs) is the essential gold standard diagnostic benchmark to confirm active maternal immune hemolysis.',
    tags: ['ABO', 'Jaundice', 'Coombs'],
    difficulty: 'Easy',
    createdAt: '2026-06-14T01:11:00Z',
  },
  {
    id: 'q_resp1',
    bankId: 'qb_respiratory',
    question: 'A 2-year-old toddler is brought to the Emergency Department at midnight with a barking cough and hoarse voice. On examination, the child is anxious, with mild inspiratory stridor audible when agitated, but no stridor at rest. Temperature is 37.6°C. What is the first-line treatment?',
    options: [
      'Inhaled Racemic Epinephrine',
      'A single dose of Oral Dexamethasone (0.15 mg/kg) or Prednisolone',
      'Intravenous Amoxicillin',
      'Continuous Salbutamol nebulization',
    ],
    correctAnswer: 1,
    explanation: 'Laryngotracheobronchitis (Croup) typically presents with barking cough, stridor, and hoarseness. Universal clinical guidelines recommend oral corticosteroids (Dexamethasone) as the gold-standard first line.',
    tags: ['Croup', 'Stridor', 'Airway'],
    difficulty: 'Medium',
    createdAt: '2026-06-14T01:15:00Z',
  },
];

export const INITIAL_MATERIALS: StudyMaterial[] = [
  {
    id: 'sm_1',
    title: 'NICE Guideline: Asthma Diagnosis in Children',
    description: 'Comprehensive guideline detailing criteria, spirometry parameters, and pediatric management pathways.',
    category: 'Guidelines',
    fileUrl: 'https://assets.mrcped.org/guidelines/NICE_Asthma_Pediatrics.pdf',
    fileSize: '1.4 MB',
    uploadedBy: 'Dr. Alice Roberts (Admin)',
    uploadedAt: '2026-06-14T01:21:00Z',
  },
  {
    id: 'sm_2',
    title: 'Neonatal Resuscitation Program (NRP) Quick Flowchart',
    description: 'Official diagnostic decision diagram charting the golden first minute resuscitation steps.',
    category: 'Handouts',
    fileUrl: 'https://assets.mrcped.org/guidelines/NRP_Neonatal_Reference.pdf',
    fileSize: '3.2 MB',
    uploadedBy: 'Dr. Alice Roberts (Admin)',
    uploadedAt: '2026-06-14T01:22:00Z',
  },
  {
    id: 'sm_3',
    title: 'High-Yield Pediatric ECG Cheat Sheet',
    description: 'Visual aids detailing QTc calculation, axis shifts, and ventricular/atrial enlargement indications.',
    category: 'Notes',
    fileUrl: 'https://assets.mrcped.org/guidelines/Pediatric_ECG_Prep.pdf',
    fileSize: '890 KB',
    uploadedBy: 'Dr. Alice Roberts (Admin)',
    uploadedAt: '2026-06-14T01:23:00Z',
  },
];

export const INITIAL_LOGS: ActivityLog[] = [
  {
    id: 'log_1',
    userId: 'u3_superadmin',
    userName: 'Senior Board Chair',
    action: 'SYSTEM_INITIALIZATION',
    metadata: '{"status":"success","modules":["Users","D1_Store","KV_Cache"]}',
    createdAt: '2026-06-13T10:00:00Z',
  },
  {
    id: 'log_2',
    userId: 'u2_admin',
    userName: 'Dr. Alice Roberts',
    action: 'QUESTION_BANK_CREATED',
    metadata: '{"bankId":"qb_cards","name":"Cardiology Core Essentials"}',
    createdAt: '2026-06-14T01:05:00Z',
  },
];
